added instance of strain sensor to controller
Code is currently broke

../../libraries/AC_AttitudeControl/AC_PosControl.cpp: In member function 'void AC_PosControl::update_z_controller_strain()':
../../libraries/AC_AttitudeControl/AC_PosControl.cpp:1144:5: error: '_strain_target' was not declared in this scope; did you mean '_roll_target'?
 1144 |     _strain_target = thr_out;
      |     ^~~~~~~~~~~~~~
      |     _roll_target
compilation terminated due to -Wfatal-errors.

../../ArduCopter/system.cpp: In member function 'void Copter::allocate_motors()':
../../ArduCopter/system.cpp:456:97: error: no matching function for call to 'AC_PosControl::AC_PosControl(AP_AHRS_View&, AP_InertialNav&, AP_MotorsMulticopter&, AC_AttitudeControl&)'
  456 |     pos_control = NEW_NOTHROW AC_PosControl(*ahrs_view, inertial_nav, *motors, *attitude_control);
      |                                                                                                 ^
compilation terminated due to -Wfatal-errors.